UPDATE shows SET title = "How I Met Your Mother" WHERE title = "How i met your mother";
UPDATE shows SET title = "Adventure Time" WHERE id = 116;
UPDATE shows SET title = "Arrow" WHERE id = 24;
UPDATE shows SET title = "Avatar: The Last Airbender" WHERE title LIKE "avatar% the%";
UPDATE shows SET title = "Brooklyn Nine-Nine" WHERE title LIKE "brooklyn%";
UPDATE shows SET title = "Community" WHERE id = 72;
UPDATE shows SET title = "Family Guy" WHERE id = 128;
UPDATE shows SET title = "Friends" WHERE id = 80;
UPDATE shows SET title = "Game of Thrones" WHERE id = 126;
UPDATE shows SET title = "Gilmore Girls" WHERE id = 148;
UPDATE shows SET title = "Grey's Anatomy" WHERE id = 147;
UPDATE shows SET title = "It's Always Sunny in Philidelphia" WHERE id = 142;
UPDATE shows SET title = "Parks and Recreation" WHERE title LIKE "park%";
UPDATE shows SET title = "Sherlock Holmes" WHERE title LIKE "sher% ho%";
UPDATE shows SET title = "Squid Game" WHERE id = 118;
UPDATE shows SET title = "The Bachelorette" WHERE id = 107;
UPDATE shows SET title = "The Crown" WHERE id = 108;
UPDATE shows SET title = "The Office" WHERE title LIKE "the%office%";
UPDATE shows SET title = "The Queen's Gambit" WHERE id = 73;
UPDATE shows SET title = "The Untamed" WHERE id = 14;
